### ISSUE TITLE
Request: preload this image from that video when starting to play the audio

### ISSUE THREAD

**Issue by dwilmer** [dbradley771/Ramble#2]
When you first play the recording of the support line for _this image_ from _that video_, the image only starts loading the first time it's shown — which isn't quick enough in my case.

I'd like to propose starting to load it, using Javascript, when the recording of the support line for _this image_ from _that video_ starts playing. This ensures that _this image_ from _that video_ gets properly displayed, ensuring no confusion about _this image_ from _that video_.

**Comment by dbradley771** [comment]
_this audio_ should display "Loading audio..." until _this image_ and _this video_ are loaded by using window.onload [here](https://github.com/dbradley771/Ramble/blob/28565f67d45ffd23287f0ff9536486a09b440194/index.html#L24). I tested the website with Chrome's dev tools by throttling my network speed, but I didn't have the issue you were describing.

Let me know if I'm not understanding you correctly.

**Comment by dwilmer** [comment]
On Firefox, _this image_ isn't loaded until you have started playing _this audio_ and _this image_ is attempted to be displayed. The behaviour in Google Chrome is indeed as expected. I'm guessing this is an optimization on Mozilla's side, to make the page load faster.

**Comment by dwilmer** [comment]
Update: I made a pull request to make Firefox behave the same as Chrome.
